# 机器人模型相关参数,给同名文件夹下使用
robot_left_ik:
  package_name: 'openarm_description'
  urdf_path: '/urdf/robot/openarm_double.urdf'
  # '/urdf/robot/openarm_double.urdf'
  # '/urdf/robot/openarm_single_control.urdf'
  # 需要锁定的关节列表，如果不需要锁定任何关节，则留空 []
  #可以先去ik读一下模型加载了什么关节
  locked_joints: #没有锁定的话直接注释掉下面的
    # - "openarm_finger_joint1"
    # - "openarm_finger_joint2"
    - "openarm_right_joint1"
    - "openarm_right_joint2"
    - "openarm_right_joint3"
    - "openarm_right_joint4" 
    - "openarm_right_joint5"
    - "openarm_right_joint6"
    - "openarm_right_joint7"
    - "openarm_left_finger_joint1"
    - "openarm_left_finger_joint2"
    - "openarm_right_finger_joint1"
    - "openarm_right_finger_joint2"
  # 末端执行器的frame名称
  end_effector_frame: "openarm_left_hand_tcp"
#  "openarm_hand_tcp"

robot_right_ik:
  package_name: 'openarm_description'
  urdf_path: '/urdf/robot/openarm_double.urdf'
  # '/urdf/robot/openarm_double.urdf'
  # '/urdf/robot/openarm_single_control.urdf'
  # 需要锁定的关节列表，如果不需要锁定任何关节，则留空 []
  #可以先去ik读一下模型加载了什么关节
  locked_joints: #没有锁定的话直接注释掉下面的
    # - "openarm_finger_joint1"
    # - "openarm_finger_joint2"
    - "openarm_left_joint1"
    - "openarm_left_joint2"
    - "openarm_left_joint3"
    - "openarm_left_joint4" 
    - "openarm_left_joint5"
    - "openarm_left_joint6"
    - "openarm_left_joint7"
    - "openarm_left_finger_joint1"
    - "openarm_left_finger_joint2"
    - "openarm_right_finger_joint1"
    - "openarm_right_finger_joint2"
  # 末端执行器的frame名称
  end_effector_frame: "openarm_right_hand_tcp"

robot_left_arm:
  left_or_right: "left" # "left" or "right"
  joint_state_sub: '/joint_states'
  joint_targer_pub: '/left_forward_position_controller/commands'
  # '/forward_position_controller/commands'
  
  control_frequency_hz: 120
  velocity_limits: [25.0, 25.0, 25.0, 25.0, 35.0, 35.0, 35.0]
  read_joints: #读取的关节列表
    - "openarm_left_joint1"
    - "openarm_left_joint2"
    - "openarm_left_joint3"
    - "openarm_left_joint4"
    - "openarm_left_joint5"
    - "openarm_left_joint6"
    - "openarm_left_joint7"
  
robot_right_arm:
  left_or_right: "right" # "left" or "right"
  joint_state_sub: '/joint_states'
  joint_targer_pub: '/right_forward_position_controller/commands'
  # '/forward_position_controller/commands'
  
  control_frequency_hz: 120
  velocity_limits: [25.0, 25.0, 25.0, 25.0, 35.0, 35.0, 35.0]
  read_joints: #读取的关节列表
    - "openarm_right_joint1"
    - "openarm_right_joint2"
    - "openarm_right_joint3"
    - "openarm_right_joint4" 
    - "openarm_right_joint5"
    - "openarm_right_joint6"
    - "openarm_right_joint7"

left_gripper_config:
  # 对应 ros2_control.yaml 中 GripperActionController 的名字
  action_name: '/left_gripper_controller/gripper_cmd'
  
  # 夹爪关节在 /joint_states 中的名字 (用于状态读取)
  joint_name: "openarm_left_finger_joint1"
  # 默认的抓取最大力 (牛顿)
  default_max_effort: 3.0
  # 夹爪的行程范围 (米)
  open_position: 0.044
  closed_position: 0.01

# ===============================================
# 右夹爪配置
# ===============================================
right_gripper_config:
  action_name: '/right_gripper_controller/gripper_cmd'
  joint_name: "openarm_right_finger_joint1"
  default_max_effort: 3.0
  open_position: 0.044
  closed_position: 0.01